#ifndef STATUS_H
#define STATUS_H

typedef enum status
{
    STATUS_SUCCESS,
    
    STATUS_LEXICAL_ERROR,
    STATUS_SYNTAX_ERROR,
    STATUS_LOGIC_ERROR,

    STATUS_FAILED_CONSTRUCTOR_ERROR,
    STATUS_FAILED_DESTRUCTOR_ERROR,
    STATUS_FAILED_COPY_ERROR,

    STATUS_LEN_EXCEEDED_ERROR,
    STATUS_INDEX_OUT_OF_BOUNDS_ERROR,
    STATUS_NULL_INPUT_ERROR,
    STATUS_INVALID_ARGUMENT_ERROR,

    STATUS_COUNT
} status;

const char *status_to_c_str(status s);

#endif /* STATUS_H */
